:icons:
= iCalendar

== Beschreibung
Ce plugin iCalendar vous permet de récupérer les événements d'un agenda gérant le format de fichier iCalendar, dans un fichier .ics : 
	
	* soit en téléchargement d'un fichier ics (google, zimbra, outlook, ...)
	* soit en Caldav (lecture seule pour l'instant avec cache locale sur la période de synchro)

L’utilisateur dispose de 3 modes de fonctionnement :

	* tester la présence de l’évènement et l’état de celui-ci via une condition dans un scénario (utilisation de l’opérateur ~ pour savoir si une chaîne de caractères en contient une autre).
	* définir au niveau des l'événement des "scénario" ou "action" qui pourront être automatiquement lancé par jeedom, soit en début ou en fin d'événement.
	* reconnaissance d'une "interaction" sur le contenu du titre ; après à vous de définir les actions produites par l'intéraction.

== Konfiguration
include::configuration.asciidoc[]

== FAQ
include::faq.asciidoc[]


== Fehlersuche
include::troubleshoting.asciidoc[]


== Fahrplan
- modification d'événement via jeedom (sans synchro avec le serveur distant dans le mode téléchargement ics) ; +
- gestion des événements + Todo (modif, création, supression) pour le mode CalDav ; +
- définir un offset à l'événement sur heure de début ou de fin ; +
- mise en place de la synchro via un daemon ; +


== Versions Dokumentation 
_Update : 27 Februar 2016_ +